### ISSUE TITLE
PowerShell access

### ISSUE THREAD

**Issue by clairernovotny** [dasMulli/SimpleGitVersion#3]
There may be other places that need access to the different version properties during a build to set other version numbers.

A script that returns a powershell object containing the calculated properties would enable additional extensibility like this:

https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/blob/master/.vsts.nightly.ci.yml#L27-L35

**Comment by dasMulli** [comment]
True but I believe that's for "proper" versioning systems like GitVersion to do. I'm not aiming to replace it.

And.. Personally I'd likely be running a ps1/sh scripts from msbuild rather than msbuild from within scripts. And maybe try `XmlPoke` on appxmanifest first :trollface:

**Comment by dasMulli** [comment]
Closing as "won't fix" - more advanced scenarios should use a more advanced implementation like Nerdbank.GitVersioning.
This SDK is meant as super simple set of msbuild tasks. Powershell etc. should call into MSBuild or read assembly metadata. (or projects shouldn't use this SDK)
